#@yaml/text-templated-strings

#@ camera_topics = [
#@     '/CAM_FRONT/image_rect_compressed',
#@     '/CAM_FRONT_LEFT/image_rect_compressed',
#@     '/CAM_FRONT_RIGHT/image_rect_compressed',
#@ ]
---
_target_: rbyte.viz.loggers.RerunLogger
schema:
  frame:
    /obs/rgb:
      Image:
        color_model: RGB

    /obs/depth:
      DepthImage:
        color_model: L

  table:
    _idx_: TimeSequenceColumn
    obs/object: Points3D
    task_successes: Scalar
