#@yaml/text-templated-strings

#@ cameras = [
#@     'CAM_FRONT',
#@     'CAM_FRONT_LEFT',
#@     'CAM_FRONT_RIGHT',
#@ ]
---
_target_: rbyte.viz.loggers.RerunLogger
schema:
  frame:
    #@ for camera in cameras:
    (@=camera@): rerun.components.ImageBufferBatch
    #@ end

  table:
    /(@=cameras[0]@)/image_rect_compressed/log_time: rerun.TimeNanosColumn
    #@ for camera in cameras:
    /(@=camera@)/image_rect_compressed/frame_idx: rerun.TimeSequenceColumn
    #@ end
    /gps/log_time: rerun.TimeNanosColumn
    /gps/latitude: rerun.components.ScalarBatch
    /gps/longitude: rerun.components.ScalarBatch
    /gps/altitude: rerun.components.ScalarBatch
