#@yaml/text-templated-strings

#@ cameras = [
#@     'cam_front_left',
#@     'cam_left_backward',
#@     'cam_right_backward',
#@ ]

---
_target_: rbyte.viz.loggers.RerunLogger
schema:
  frame:
    #@ for camera in cameras:
    (@=camera@):
      rerun.components.ImageBufferBatch:
        color_model: RGB
    #@ end

  table:
    #@ for camera in cameras:
    ImageMetadata.(@=camera@).frame_idx: rerun.TimeSequenceColumn
    ImageMetadata.(@=camera@).time_stamp: rerun.TimeNanosColumn
    #@ end
    VehicleMotion.time_stamp: rerun.TimeNanosColumn
    VehicleMotion.speed: rerun.components.ScalarBatch
