#@yaml/text-templated-strings

#@ cameras = [
#@     'cam_front_left',
#@ ]
---
_target_: rbyte.viz.loggers.RerunLogger
_convert_: all
_recursive_: false
application_id: [meta, input_id]
schema:
  #@ for/end camera in cameras:
  (@=camera@):
    - _target_: rerun.Image.columns
      buffer: [data, (@=camera@)]
    - static: true
      entity:
        _target_: rerun.Image.from_fields
        format:
          _target_: rerun.components.ImageFormat
          height: 324
          width: 576
          color_model: RGB
          channel_datatype: u8

  _idx_:
    _target_: rerun.TimeSequenceColumn
    times: [data, _idx_]

  #@ for entity, key in {
  #@     "brake": "control.brake",
  #@     "steer": "control.steer",
  #@     "acceleration": "state.acceleration.value",
  #@     "velocity": "state.velocity.value",
  #@ }.items():
  (@=entity@):
    _target_: rerun.Scalar.columns
    scalar: [data, "(@=key@)"]
  #@ end
