#@yaml/text-templated-strings

#@ cameras = [
#@     'cam_front_left',
#@ ]
---
_target_: rbyte.viz.loggers.RerunLogger
_recursive_: true
_convert_: all
schema:
  frame:
    #@ for camera in cameras:
    (@=camera@):
      Image:
        color_model: RGB
    #@ end

  table:
    _idx_: TimeSequenceColumn
    control.brake: Scalar
    control.steer: Scalar
    control.throttle: Scalar
    state.acceleration.value: Scalar
    state.velocity.value: Scalar
