---
_target_: rbyte.viz.loggers.RerunLogger
_convert_: all
_recursive_: false
application_id: [meta, input_id]
schema:
  idx:
    _target_: rerun.TimeSequenceColumn
    times: [data, _idx_]

  obs/agentview_image:
    - _target_: rerun.Image.columns
      buffer: [data, obs/agentview_image]

    - static: true
      entity:
        _target_: rerun.Image.from_fields
        format:
          _target_: rerun.components.ImageFormat
          height: 84
          width: 84
          color_model: RGB
          channel_datatype: u8

  obs/robot0_eef_pos:
    _target_: rerun.Points3D.columns
    positions: [data, obs/robot0_eef_pos]
