#@yaml/text-templated-strings

#@ camera_entities = {
#@     "CAM_FRONT_LEFT": "/world/ego_vehicle/CAM_FRONT_LEFT",
#@     "CAM_FRONT": "/world/ego_vehicle/CAM_FRONT",
#@     "CAM_FRONT_RIGHT": "/world/ego_vehicle/CAM_FRONT_RIGHT",
#@ }
---
_target_: rbyte.viz.loggers.RerunLogger
schema:
  frame:
    #@ for camera in camera_entities.keys():
    (@=camera@):
      Image:
        color_model: RGB
    #@ end

  table:
    #@ for camera_entity in camera_entities.values():
    (@=camera_entity@)/_idx_: TimeSequenceColumn
    (@=camera_entity@)/timestamp: TimeNanosColumn
    #@ end
    /world/ego_vehicle/LIDAR_TOP/timestamp: TimeNanosColumn
    /world/ego_vehicle/LIDAR_TOP/Position3D: Points3D

spawn: true
blueprint:
  _target_: rerun.blueprint.Blueprint
  _args_:
    - _target_: rerun.blueprint.Vertical
      contents:
        - _target_: rerun.blueprint.Spatial3DView
          origin: table

        - _target_: rerun.blueprint.Horizontal
          contents:
            #@ for camera in camera_entities.keys():
            - _target_: rerun.blueprint.Spatial2DView
              name: #@ camera
              origin: #@ "frame/{}".format(camera)
            #@ end
