#@yaml/text-templated-strings

#@ camera_entities = {
#@     "CAM_FRONT": "/world/ego_vehicle/CAM_FRONT",
#@     "CAM_FRONT_LEFT": "/world/ego_vehicle/CAM_FRONT_LEFT",
#@     "CAM_FRONT_RIGHT": "/world/ego_vehicle/CAM_FRONT_RIGHT",
#@ }
---
_target_: rbyte.viz.loggers.RerunLogger
_convert_: all
_recursive_: false
application_id: [meta, input_id]
spawn: true
schema:
  #@ entity = camera_entities.values()[0]
  (@=entity@)/timestamp:
    _target_: rerun.TimeNanosColumn
    times: [data, "(@=entity@)/timestamp"]

  #@ for/end entity in camera_entities.values():
  (@=entity@)/_idx_:
    _target_: rerun.TimeSequenceColumn
    times: [data, "(@=entity@)/_idx_"]

  #@ for/end camera in camera_entities.keys():
  (@=camera@):
    - _target_: rerun.Image.columns
      buffer: [data, (@=camera@)]
    - static: true
      entity:
        _target_: rerun.Image.from_fields
        format:
          _target_: rerun.components.ImageFormat
          height: 900
          width: 1600
          color_model: RGB
          channel_datatype: u8

  /world/ego_vehicle/LIDAR_TOP/Position3D:
    _target_: rerun.Points3D.columns
    positions: [data, /world/ego_vehicle/LIDAR_TOP/Position3D]
