#! https://github.com/foxglove/nuscenes2mcap

#@yaml/text-templated-strings

#@ inputs = [
#@     'NuScenes-v1.0-mini-scene-0103',
#@ ]

#@ cameras = [
#@     'CAM_FRONT',
#@     'CAM_FRONT_LEFT',
#@     'CAM_FRONT_RIGHT',
#@ ]
---
_target_: rbyte.Dataset
_convert_: all
_recursive_: false
inputs:
  #@ for input_id in inputs:
  (@=input_id@):
    frame:
      #@ for source_id in cameras:
      (@=source_id@):
        index_column: /(@=source_id@)/image_rect_compressed/frame_idx
        reader:
          _target_: rbyte.io.frame.mcap.McapFrameReader
          path: "${data_dir}/(@=input_id@).mcap"
          topic: /(@=source_id@)/image_rect_compressed
          message_decoder_factory:
            _target_: mcap_protobuf.decoder.DecoderFactory
          frame_decoder:
            _target_: simplejpeg.decode_jpeg
            _partial_: true
            colorspace: rgb
            fastdct: true
            fastupsample: true
      #@ end

    table:
      path: "${data_dir}/(@=input_id@).mcap"
      builder:
        _target_: rbyte.io.table.TableBuilder
        reader:
          _target_: rbyte.io.table.mcap.McapProtobufTableReader
          _recursive_: false
          _convert_: all
          fields:
            #@ for camera in cameras:
            /(@=camera@)/image_rect_compressed:
              log_time:
                _target_: polars.Datetime
                time_unit: ns
            #@ end

            /gps:
              log_time:
                _target_: polars.Datetime
                time_unit: ns

              latitude: polars.Float64
              longitude: polars.Float64
              altitude: polars.Float64

        merger:
          _target_: rbyte.io.table.TableMerger
          separator: /
          merge:
            /(@=cameras[0]@)/image_rect_compressed:
              log_time:
                method: ref

            #@ for camera in cameras[1:]:
            /(@=camera@)/image_rect_compressed:
              log_time:
                method: ref
              frame_idx:
                method: asof
                tolerance: 10ms
                strategy: nearest
            #@ end

            /gps:
              log_time:
                method: ref
              latitude:
                method: asof
                tolerance: 1000ms
                strategy: nearest
              longitude:
                method: asof
                tolerance: 1000ms
                strategy: nearest
              altitude:
                method: asof
                tolerance: 1000ms
                strategy: nearest

        filter: !!null
        cache:
          _target_: rbyte.utils.dataframe.DataframeDiskCache
          directory: /tmp/rbyte-cache
          size_limit: 1GiB
  #@ end

sample_builder:
  _target_: rbyte.sample.builder.GreedySampleTableBuilder
  index_column: /(@=cameras[0]@)/image_rect_compressed/frame_idx
  length: 1
  stride: 1
  min_step: 1
  filter: !!null
