#@yaml/text-templated-strings

#@ drives = [
#@     'Niro098-HQ/2024-01-22--09-03-16',
#@ ]

#@ cameras = [
#@     'cam_front_left',
#@     'cam_left_backward',
#@     'cam_right_backward',
#@ ]
---
_target_: rbyte.Dataset
_recursive_: false
_convert_: all
inputs:
  #@ for input_id in drives:
  (@=input_id@):
    frame:
      #@ for source_id in cameras:
      (@=source_id@):
        index_column: "ImageMetadata.(@=source_id@).frame_idx"
        reader:
          _target_: rbyte.io.frame.DirectoryFrameReader
          _recursive_: true
          path: "${data_dir}/(@=input_id@)/frames/(@=source_id@).pii.mp4/576x324/{:09d}.jpg"
          frame_decoder:
            _target_: simplejpeg.decode_jpeg
            _partial_: true
            colorspace: rgb
            fastdct: true
            fastupsample: true
        #@ end

    table:
      builder:
        _target_: rbyte.io.table.TableBuilder
        _convert_: all
        readers:
          - path: ${data_dir}/(@=input_id@)/metadata.log
            reader:
              _target_: rbyte.io.table.yaak.YaakMetadataTableReader
              _recursive_: false
              fields:
                rbyte.io.table.yaak.proto.sensor_pb2.ImageMetadata:
                  time_stamp:
                    _target_: polars.Datetime
                    time_unit: ns

                  frame_idx: polars.UInt32
                  camera_name:
                    _target_: polars.Enum
                    categories:
                      - cam_front_center
                      - cam_front_left
                      - cam_front_right
                      - cam_left_forward
                      - cam_right_forward
                      - cam_left_backward
                      - cam_right_backward
                      - cam_rear

                rbyte.io.table.yaak.proto.can_pb2.VehicleMotion:
                  time_stamp:
                    _target_: polars.Datetime
                    time_unit: ns

                  speed: polars.Float32
                  gear:
                    _target_: polars.Enum
                    categories: ["0", "1", "2", "3"]

          - path: ${data_dir}/(@=input_id@)/ai.mcap
            reader:
              _target_: rbyte.io.table.mcap.McapTableReader
              _recursive_: false
              decoder_factories: [rbyte.utils.mcap.ProtobufDecoderFactory]
              fields:
                /ai/safety_score:
                  clip.end_timestamp:
                    _target_: polars.Datetime
                    time_unit: ns

                  score: polars.Float32

        merger:
          _target_: rbyte.io.table.TableAligner
          separator: "."
          merge:
            ImageMetadata.(@=cameras[0]@):
              time_stamp:
                method: ref

            #@ for camera in cameras[1:]:
            ImageMetadata.(@=camera@):
              time_stamp:
                method: ref

              frame_idx:
                method: asof
                tolerance: 20ms
                strategy: nearest
            #@ end

            VehicleMotion:
              time_stamp:
                method: ref
              speed:
                method: interp
              gear:
                method: asof
                tolerance: 100ms

            /ai/safety_score:
              clip.end_timestamp:
                method: ref

              score:
                method: asof
                tolerance: 100ms
                strategy: nearest

        filter: |
          `VehicleMotion.gear` == '3'

        cache:
          _target_: rbyte.utils.dataframe.DataframeDiskCache
          directory: /tmp/rbyte-cache
          size_limit: 1GiB
  #@ end

sample_builder:
  _target_: rbyte.sample.builder.GreedySampleTableBuilder
  index_column: ImageMetadata.(@=cameras[0]@).frame_idx
  length: 6
  stride: 10
  min_step: 6
  filter: |
    array_lower(`VehicleMotion.speed`) > 50
