---
#@ drives = [
#@    'Niro096-HQ/2023-01-11--13-47-36',
#@    'Niro101-HQ/2022-12-25--09-58-33',
#@    'Niro101-HQ/2022-12-30--09-23-51',
#@    'Niro101-HQ/2022-12-31--09-57-24',
#@    'Niro101-HQ/2023-01-01--09-31-43',
#@    'Niro101-HQ/2023-01-01--12-01-47',
#@    'Niro101-HQ/2023-03-27--14-58-37',
#@    'Niro101-HQ/2023-04-02--10-08-57',
#@    'Niro101-HQ/2023-04-02--13-27-47',
#@    'Niro101-HQ/2023-04-06--14-43-08',
#@ ]

#@ cameras = ['cam_front_left', 'cam_left_forward', 'cam_right_forward']

_target_: rbyte.Dataset
_recursive_: false
config:
  inputs:
    #@ for drive in drives:
    - id: #@ drive
      sources:
        frame:
          #@ for camera in cameras:
          - id: #@ camera
            index_column: "image.${.id}.frame_idx"
            reader:
              _target_: rbyte.io.frame.jpeg.JpegFrameReader
              path: "${data_dir}/${.....id}/frames/${..id}.defish.mp4/576x324/{:09d}.jpg"
            #@ end

        table:
          path: ${data_dir}/${...id}/metadata.log
          builder:
            _target_: rbyte.io.table.yaak.YaakMetadataTableBuilder
            _recursive_: false
            config:
              cameras: #@ cameras
              select:
                - message:
                    type: rbyte.io.table.yaak.proto.sensor_pb2.ImageMetadata
                    alias: image
                  fields:
                    - name: time_stamp

                    - name: frame_idx
                      merge:
                        method: asof
                        tolerance: 30ms

                    - name: camera_name
                      partition: true

                - message:
                    type: rbyte.io.table.yaak.proto.can_pb2.VehicleState
                    alias: vehicle_state
                  fields:
                    - name: time_stamp

                    - name: turn_signal
                      merge:
                        method: asof
                        tolerance: 100ms

                - message:
                    type: rbyte.io.table.yaak.proto.can_pb2.VehicleMotion
                    alias: vehicle_motion
                  fields:
                    - name: time_stamp

                    - name: speed
                      merge:
                        method: interp

                    - name: gas_pedal_normalized
                      merge:
                        method: interp

                    - name: brake_pedal_normalized
                      merge:
                        method: interp

                    - name: steering_angle_normalized
                      merge:
                        method: interp

                    - name: gear
                      merge:
                        method: asof
                        tolerance: 100ms

                - message:
                    type: rbyte.io.table.yaak.proto.sensor_pb2.Gnss
                    alias: gnss
                  fields:
                    - name: time_stamp

                    - name: heading
                      merge:
                        method: asof
                        tolerance: 100ms

              merge:
                reference:
                  key:
                    [
                      rbyte.io.table.yaak.proto.sensor_pb2.ImageMetadata,
                      cam_front_left,
                    ]
                  column: time_stamp

              filter: |
                `vehicle_motion.gear` == 3

              cache:
                _target_: rbyte.utils.DataframeDiskCache
                directory: /tmp/rbyte-cache
                size_limit: "10 GiB"
                #@ end

  samples:
    builder:
      _target_: rbyte.sample.builder.GreedySampleTableBuilder
      config:
        index_column: image.cam_front_left.frame_idx
        length: 1
        stride: 1
        min_step: 1
        filter: !!null
