#! https://jkk-research.github.io/dataset/jkk_dataset_02

#@yaml/text-templated-strings
---
_target_: rbyte.io.table.TableBuilder
reader:
  _target_: rbyte.io.table.mcap.McapRos2TableReader
  _recursive_: false
  _convert_: all
  fields:
    /nissan/vehicle_speed:
      log_time:
        _target_: polars.Datetime
        time_unit: ns

      data:

    /nissan/gps/duro/current_pose:
      log_time:
        _target_: polars.Datetime
        time_unit: ns

      pose.position.x:
      pose.position.y:
      pose.position.z:
      pose.orientation.x:
      pose.orientation.y:
      pose.orientation.z:
      pose.orientation.w:

merger:
  _target_: rbyte.io.table.TableMerger
  separator: /
  merge:
    /nissan/vehicle_speed:
      log_time:
        method: ref

    /nissan/gps/duro/current_pose:
      log_time:
        method: ref
      pose.position.x:
        method: interp
      pose.position.y:
        method: interp
      pose.position.z:
        method: interp
      pose.orientation.x:
        method: interp
      pose.orientation.y:
        method: interp
      pose.orientation.z:
        method: interp
      pose.orientation.w:
        method: interp

filter: !!null

cache:
  _target_: rbyte.utils.dataframe.DataframeDiskCache
  directory: /tmp/rbyte-cache
  size_limit: 1GiB
