#@yaml/text-templated-strings

#@ cameras = [
#@     'CAM_FRONT',
#@     'CAM_FRONT_LEFT',
#@     'CAM_FRONT_RIGHT',
#@ ]
---
_target_: rbyte.io.table.TableBuilder
reader:
  _target_: rbyte.io.table.mcap.McapProtobufTableReader
  _recursive_: false
  _convert_: all
  fields:
    #@ for camera in cameras:
    /(@=camera@)/image_rect_compressed:
      log_time:
        _target_: polars.Datetime
        time_unit: ns
    #@ end

    /gps:
      log_time:
        _target_: polars.Datetime
        time_unit: ns

      latitude: polars.Float64
      longitude: polars.Float64
      altitude: polars.Float64

merger:
  _target_: rbyte.io.table.TableMerger
  separator: /
  merge:
    /(@=cameras[0]@)/image_rect_compressed:
      log_time:
        method: ref

    #@ for camera in cameras[1:]:
    /(@=camera@)/image_rect_compressed:
      log_time:
        method: ref
      frame_idx:
        method: asof
        tolerance: 10ms
        strategy: nearest
    #@ end

    /gps:
      log_time:
        method: ref
      latitude:
        method: asof
        tolerance: 1000ms
        strategy: nearest
      longitude:
        method: asof
        tolerance: 1000ms
        strategy: nearest
      altitude:
        method: asof
        tolerance: 1000ms
        strategy: nearest

filter: !!null
cache:
  _target_: rbyte.utils.dataframe.DataframeDiskCache
  directory: /tmp/rbyte-cache
  size_limit: 1GiB
