---
_target_: rbyte.io.frame.DirectoryFrameReader
_recursive_: true
path: ???
frame_decoder:
  _target_: simplejpeg.decode_jpeg
  _partial_: true
  colorspace: rgb
  fastdct: true
  fastupsample: true
