---
_target_: rbyte.io.table.TableBuilder
_convert_: all
readers:
  - path: ???
    reader:
      _target_: rbyte.io.table.JsonTableReader
      _recursive_: false
      fields:
        records:
          _idx_:
          control.brake:
          control.throttle:
          control.steer:
          state.velocity.value:
          state.acceleration.value:

      transforms:
        - _target_: rbyte.io.table.transforms.FpsResampler
          source_fps: 20
          target_fps: 30

merger:
  _target_: rbyte.io.table.TableConcater
  method: vertical

filter: |-
  `control.throttle` > 0.5
