---
_target_: rbyte.io.table.TableBuilder
_convert_: all
readers:
  - path: ???
    reader:
      _target_: rbyte.io.table.Hdf5TableReader
      _recursive_: false
      fields:
        /data/demo_0:
          _idx_:
          actions:
          dones:
          obs/robot0_eef_pos:
          rewards:
          states:

merger:
  _target_: rbyte.io.table.TableConcater
  method: vertical
