#@yaml/text-templated-strings

#@ camera_entities = {
#@     "CAM_FRONT_LEFT": "/world/ego_vehicle/CAM_FRONT_LEFT",
#@     "CAM_FRONT": "/world/ego_vehicle/CAM_FRONT",
#@     "CAM_FRONT_RIGHT": "/world/ego_vehicle/CAM_FRONT_RIGHT",
#@ }
---
_target_: rbyte.io.table.TableBuilder
_convert_: all
readers:
  - path: ???
    reader:
      _target_: rbyte.io.table.RrdTableReader
      _recursive_: false
      index: timestamp
      contents:
        #@ for entity in camera_entities.values():
        (@=entity@):
          - _idx_
        #@ end

        /world/ego_vehicle/LIDAR_TOP:
          - Position3D

merger:
  _target_: rbyte.io.table.TableAligner
  separator: /
  merge:
    #@ entity = camera_entities.values()[0]
    (@=entity@):
      timestamp:
        method: ref

    #@ for entity in camera_entities.values()[1:]:
    (@=entity@):
      timestamp:
        method: ref

      _idx_:
        method: asof
        strategy: nearest
        tolerance: 20ms
    #@ end

    /world/ego_vehicle/LIDAR_TOP:
      timestamp:
        method: ref

      Position3D:
        method: asof
        strategy: nearest
        tolerance: 20ms
