---
defaults:
  - /dataloader: ???
  - /dataset: ???
  - _self_

dataloader:
  dataset: ${dataset}
  shuffle: false
  batch_size: 64
  num_workers: ???
  collate_fn:
    _target_: hydra.utils.get_method
    path: rbyte.dataloader.collate_identity
  multiprocessing_context: forkserver
