---
defaults:
  - frame_reader: !!null
  - _self_

batch_size: 1
application_id: rbyte
entity_path: frames
frame_config:
  Image:
    pixel_format: !!null
    color_model: !!null

hydra:
  output_subdir: !!null
  run:
    dir: .
