#! https://app.rerun.io/examples/nuscenes_dataset.rrd

#@yaml/text-templated-strings

#@ inputs = [
#@     'nuscenes',
#@ ]

#@ camera_entities = {
#@     'CAM_FRONT_LEFT': '/world/ego_vehicle/CAM_FRONT_LEFT',
#@     'CAM_FRONT': '/world/ego_vehicle/CAM_FRONT',
#@     'CAM_FRONT_RIGHT': '/world/ego_vehicle/CAM_FRONT_RIGHT',
#@ }
---
_target_: rbyte.Dataset
_convert_: all
_recursive_: false
inputs:
  #@ for input_id in inputs:
  (@=input_id@):
    frame:
      #@ for camera, entity in camera_entities.items():
      (@=camera@):
        index_column: (@=entity@)/_idx_
        reader:
          _target_: rbyte.io.frame.RrdFrameReader
          path: "${data_dir}/(@=input_id@).rrd"
          index: timestamp
          entity_path: (@=entity@)
          frame_decoders:
            image/jpeg:
              _target_: simplejpeg.decode_jpeg
              _partial_: true
              colorspace: rgb
              fastdct: true
              fastupsample: true
      #@ end

    table:
      builder:
        _target_: rbyte.io.table.TableBuilder
        _convert_: all
        readers:
          - path: "${data_dir}/(@=input_id@).rrd"
            reader:
              _target_: rbyte.io.table.RrdTableReader
              _recursive_: false
              index: timestamp
              contents:
                #@ for entity in camera_entities.values():
                (@=entity@):
                  - _idx_
                #@ end

                /world/ego_vehicle/LIDAR_TOP:
                  - Position3D

        merger:
          _target_: rbyte.io.table.TableAligner
          separator: /
          merge:
            #@ entity = camera_entities.values()[0]
            (@=entity@):
              timestamp:
                method: ref

            #@ for entity in camera_entities.values()[1:]:
            (@=entity@):
              timestamp:
                method: ref

              _idx_:
                method: asof
                strategy: nearest
                tolerance: 20ms
            #@ end

            /world/ego_vehicle/LIDAR_TOP:
              timestamp:
                method: ref

              Position3D:
                method: asof
                strategy: nearest
                tolerance: 20ms

        filter: |
          `/world/ego_vehicle/CAM_FRONT/timestamp` between '2018-07-24 03:28:48' and '2018-07-24 03:28:50'
  #@ end

sample_builder:
  _target_: rbyte.sample.builder.GreedySampleTableBuilder
  index_column: (@=camera_entities.values()[0]@)/_idx_
  length: 1
  stride: 1
  min_step: 1
  filter: !!null
