---
name: CI

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop -c bash --noprofile --norc -eo pipefail {0}

    steps:
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.YAAK_IDL_REPO_SSH_KEY }}

      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false
          lfs: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: uv lock

      - uses: actions/cache@v5
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - run: uv sync --all-extras --group check --group test
      - run: just build
      - run: just check
      - run: git lfs checkout
      - run: just test
      - run: uv cache prune --ci
